- hosts: localhost
  remote_user: root
  vars:
    # Specify whether we want to create things or destroy them
    state: "absent"
    # Connection parameters
    username : admin
    password : password
    apiUrl : "https://15.4.7.1"
    verifySsl: False
    # Foreman configuration parameters
    smartProxyFqdn: "foreman.foobar.com"
    pxqFqdn: "pxe.foobar.com"
    # Iso Mirror / Install media parameters
    mediaName : "xcp-ng"
    osFamily : "Xenserver"
    mirrorPath : "http://15.4.7.1:8080/xcp-ng/$major.$minor/os/$arch"
    templateDir: "http://15.4.7.1:8080/foreman_templates"
    major: 7
    minor: 5

  tasks:

  # ================================================================================
  # Delete and Un-link the Foreman objects required to PXE boot a host
  # ================================================================================

  - name: "UnLink the PXE Operating System with the provisioning templates"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        operatingsystem:
          name: "PXE_Operating_System"
          major: "{{ major }}"
          minor: "{{ minor }}"
          description: "here is a description"
          family: "{{ osFamily }}"
          password_hash: "SHA256"
          architecture_ids: []
          config_template_ids: []
          provisioning_template_ids: []
          medium_ids: []
          ptable_ids: []
      state: "present"
    register: os_results

  - name: "Unlink the PXE Boot Partitioning Table with the PXE Operating System"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        ptable:
          name: "XCP-ng Partitioning Table"
          os_family: "{{ osFamily }}"
          operatingsystem_ids: []
          layout: "This is a dummy layout to make the api happy"
          locked: false
      state: "present"

  - name: "Delete PXE Boot Partitioning Table"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        ptable:
          name: "XCP-ng Partitioning Table"
      state: "{{ state }}"

  - name: "Unlink the PXE PXELinux Provisioning Template with the PXE Operating System"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        provisioning_template:
          name: "PXE PXELinux Provisioning Template"
          template: "This is a dummy template to make the api happy"
          locked: false
          template_kind_id: 5
      state: "present"
    register: provisioning_template_results

  - name: "Delete the default Provisioning Template for the PXE Operating system"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        os_default_template:
          operatingsystem_id: "{{ os_results.actual_record.operatingsystem.id }}"
          template_kind_id: "{{ provisioning_template_results.actual_record.provisioning_template.template_kind_id }}"
          provisioning_template_id: "{{ provisioning_template_results.actual_record.provisioning_template.id }}"
        dependencies:
          - operatingsystem:
              id: "{{ os_results.actual_record.operatingsystem.id }}"
              name: "{{ os_results.actual_record.operatingsystem.name }}"
              description: "{{ os_results.actual_record.operatingsystem.description }}"
      state: "{{ state }}"
    register: os_link_results

  - name: "Delete the PXE PXELinux Provisioning Template"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        provisioning_template:
          name: "PXE PXELinux Provisioning Template"
      state: "{{ state }}"
    register: provisioning_template_results

  - name: "Unlink the PXE OS Answer File with the PXE Operating System"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        provisioning_template:
          name: "PXE OS Answer File"
          locked: false
          template: "This is a dummy template to make the api happy"
          template_kind_id: 5
      state: "present"

  - name: "Delete PXE OS Answer File"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        provisioning_template:
          name: "PXE OS Answer File"
      state: "{{ state }}"

  # ================================================================================
  # Delete the Foreman objects required to create a host (opposite order from creation)
  # ================================================================================

  - name: "Delete PXE Boot Installation Media"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        medium:
          name: "{{ mediaName }}"
      state: "{{ state }}"
    register: medium_results

  - name: "Delete PXE Operating System"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        operatingsystem:
          name: "PXE_Operating_System"
      state: "{{ state }}"
    register: os_results

  - name: "Unlink PXE Boot Subnet from the smart proxy"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        subnet:
          name: "PxeSubnet"
          network: "15.0.0.0"
          mask: "255.0.0.0"
          gateway: "15.1.1.1"
          dns_primary: "15.4.7.1"
          dns_secondary: "15.1.1.1"
          boot_mode: "DHCP"
          domain_ids: []
          dhcp_id:  ""
          tftp_id:  ""
          dns_id:  ""
      state: "present"

  - name: "Delete PXE Boot Subnet"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        subnet:
          name: "PxeSubnet"
      state: "{{ state }}"

  - name: "Unlink PXE Boot Domain with the SMART Proxy"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        domain:
          name: "{{ pxqFqdn }}"
          dns_id: ""
      state: "present"
    register: domain_results

  - name: "Delete PXE Boot Domain"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        domain:
          name: "{{ pxqFqdn }}"
      state: "{{ state }}"
    register: domain_results

  # Dont telete the architecture because we are using it elsewhere
  # - name: "Delete PXE Boot Architecture"
  #   AnsibleForemanModule:
  #     username: "{{ username }}"
  #     password: "{{ password }}"
  #     apiUrl: "{{ apiUrl }}"
  #     verifySsl: "{{ verifySsl }}"
  #     record:
  #       architecture:
  #         name: "x86_64"
  #     state: "{{ state }}"
  #   register: architecture_results













