- hosts: localhost
  remote_user: root
  vars:
    # Specify whether we want to create things or destroy them
    state: "present"
    # Connection parameters
    username: admin
    password: password
    apiUrl: "https://15.4.7.1"
    verifySsl: False
    # Foreman configuration parameters
    smartProxyFqdn: "foreman.foobar.com"
    pxqFqdn: "pxe.foobar.com"

  tasks:

  - name: "Unlink PXE Boot Subnet from the smart proxy"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        subnet:
          name: "PxeSubnet"
          network: "15.0.0.0"
          mask: "255.0.0.0"
          gateway: "15.1.1.1"
          dns_primary: "15.4.7.1"
          dns_secondary: "15.1.1.1"
          boot_mode: "DHCP"
          domain_ids: []
          dhcp_id:  ""
          tftp_id:  ""
          dns_id:  ""
      state: "present"

  - name: "Delete PXE Boot Subnet"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        subnet:
          name: "PxeSubnet"
      state: "{{ state }}"

  - name: "Unlink PXE Boot Domain with the SMART Proxy"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        domain:
          name: "{{ pxqFqdn }}"
          dns_id: ""
      state: "present"
    register: domain_results

  - name: "Delete PXE Boot Domain"
    AnsibleForemanModule:
      username: "{{ username }}"
      password: "{{ password }}"
      apiUrl: "{{ apiUrl }}"
      verifySsl: "{{ verifySsl }}"
      record:
        domain:
          name: "{{ pxqFqdn }}"
      state: "{{ state }}"
    register: domain_results














