- hosts: localhost
  remote_user: root
  tasks:
    - name: This is my task to execute my module
      AnsibleForemanModule:
        apiUrl: https://15.4.7.1
        username: admin
        password: password
        verifySsl: false
        record:
          environment:
            name: test__Ensure_Environment_Present_Success_DoesNotExist
        state: absent
        action: query
